protected/modules/admin/controllers/GraficaController.php
<?php
namespace app\modules\admin\controllers;

use Yii;
use yii\web\Response;
use app\modules\admin\controllers\AbstractController;
use app\modules\admin\models\ApiIngresso;
use app\models\ApiCarrinho;
use app\models\EventosModel;

/**
 * Controller de gráfica
 */
class GraficaController extends AbstractController
{
    public $enableCsrfValidation = false;
    
    /**
     * Página principal para a gráfica
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Reservar um conjunto de QR-Codes para um determinado evento
     */
    public function actionReservar()
    {
        try {
            $retorno = '';
            $vendas = [];
            $totais = [];
            if (Yii::$app->request->post()) {
                $ingresso = new ApiIngresso();
                if (Yii::$app->request->post('idEvento') && !Yii::$app->request->post('codigoCompra')) {
                    $totais = (new ApiIngresso)->consultarTotais(['id_agenda' => Yii::$app->request->post('idEvento')]);
                    if ($totais->successo == '1' && isset($totais->objeto->totais->ultima_compra) && !empty($totais->objeto->totais->ultima_compra)) {
                        $ultimaCompra = (new ApiCarrinho)->consultarVendasFiltro(['codigo' => $totais->objeto->totais->ultima_compra]);
                        $vendas = (new ApiCarrinho)->consultarVendasFiltro(['data_ini' => date('d-m-Y H:i:s', strtotime('+10 seconds', strtotime(str_replace('/', '-', $ultimaCompra->objeto[0]->vendas->data))))]);
                    } else {
                        $vendas = (new ApiCarrinho)->consultarVendasFiltro(['data_ini' => '27-11-2017']);
                    }
                }
                if (Yii::$app->request->post('idEvento') && Yii::$app->request->post('codigoCompra')) {
                    $reserva = $ingresso->reservar([
                        'id_agenda' => Yii::$app->request->post('idEvento'), 
                        'lote_origem' => 'mineirao_'.time(),
                        'codigo_compra_limite' => Yii::$app->request->post('codigoCompra'), 
                    ]);
                    if ($reserva->successo == '1') {
                        $retorno = ['tipo' => 'success', 'msg' => 'Reserva: ' . $reserva->objeto->msg . '. Alterados: ' . $reserva->objeto->alterados];
                    }
                    if ($reserva->successo == 0)
                        $retorno = ['tipo' => 'warning', 'msg' => $reserva->erro->mensagem];
                }
            }
            $eventos = (new EventosModel())->listaEventos(['ativo' => '1']);
            return $this->render('lote-reservar', [
                'eventos' => $eventos,
                'retorno' => $retorno,
                'vendas' => $vendas,
                'ultimo_corte' => isset($totais->objeto->totais->ultima_compra) ? $totais->objeto->totais->ultima_compra : '0'
            ]);
            
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro - Reserva de ingressos', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Registrar lote de cartões como "em Produção"
     */
    public function actionLoteProducao()
    {
        try {
            $eventos = (new EventosModel())->listaEventos(['ativo' => '1']);
            $ingressos = '';
            $lotes = '';
            if (Yii::$app->request->post()) {
                $ingresso = new ApiIngresso();
                $ingressos = $ingresso->consultar([
                    'id_agenda' => Yii::$app->request->post('producao_evento'), 
                    'status' => 'R'
                ]);
                if ($ingressos->successo == '1') {
                    $lotes = $ingresso->registrosLote($ingressos);
                }
            }
            return $this->render('lote-producao', [
                'codigo_evento' => Yii::$app->request->post('producao_evento') != null ? Yii::$app->request->post('producao_evento') : '',
                'eventos' => $eventos,
                'ingressos' => $ingressos, 
                'lotes' => $lotes,
            ]);
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro - Lotes em Produção', 'message' => $e->getMessage()]);
        }
    }
    
    /**
     * Exportar informações para arquivo CSV
     * @param integer $evento Id do evento a que se refere o ingresso
     * @param string $lote Identificador do lote a ser gerado
     * @param string $status Identificador da situação dos ingressos a serem pesquisados
    */
    public function actionExportarCsv($evento='', $lote='', $status='')
    {
        try {
            if (empty($evento) || empty($lote) || empty($status)) {
                exit('Faltam informações para gerar o arquivo .csv do lote.');
            }
            $ingressos = (new ApiIngresso())->consultar([
                'id_agenda' => $evento,
                'lote_origem' => $lote, 
                'status' => $status,
            ]);
            if ($ingressos->successo == '1') {
                header('Content-Type: text/csv; charset=utf-8');
                header('Content-Disposition: attachment; filename=lote_ingresso_' . date('d-m-Y_H-i-s') . '.csv');
                $output = fopen('php://output', 'w');
                $arrCabecalho=['Qrcode', 'Nome do ocupante', 'Bloco', 'Fileira', 'Cadeira'];
                if($status=='A')
                    $arrCabecalho=['Qrcode', 'RFID', 'Nome do ocupante', 'Bloco', 'Fileira', 'Cadeira'];
                fputcsv($output, $arrCabecalho, ';');
                foreach ($ingressos->objeto as $index => $ingresso) {
                    $infoProduto = !empty($ingresso->produto) ? explode(' ', $ingresso->produto) : [];
                    $arrRow=[
                        isset($ingresso->qrcode) && !empty($ingresso->qrcode) ? $ingresso->qrcode : '-', 
                        isset($ingresso->ocupante_nome) && !empty($ingresso->ocupante_nome) ? utf8_decode($ingresso->ocupante_nome) : '-', 
                        isset($infoProduto[3]) && !empty($infoProduto[3]) ? $infoProduto[3] : '-', 
                        isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 0, 1) : '-', 
                        isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 1, strlen($infoProduto[1])) : '-'
                    ];
                    if($status=='A')
                        $arrRow=[
                            isset($ingresso->qrcode) && !empty($ingresso->qrcode) ? $ingresso->qrcode : '-', 
                            isset($ingresso->codigo) && !empty($ingresso->codigo) ? $ingresso->codigo : '-', 
                            isset($ingresso->ocupante_nome) && !empty($ingresso->ocupante_nome) ? utf8_decode($ingresso->ocupante_nome) : '-', 
                            isset($infoProduto[3]) && !empty($infoProduto[3]) ? $infoProduto[3] : '-', 
                            isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 0, 1) : '-', 
                            isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 1, strlen($infoProduto[1])) : '-'
                        ];
                    fputcsv($output, $arrRow, ';');
                }
                die();
            }
            exit('Não há ingressos disponíveis para as informações fornecidas.');
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro - Geração de arquivo .csv', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Método alterantivo para exportar informações para arquivo CSV - não pede o lote e adiciona coluna do código RFID
     * @param integer $evento Id do evento a que se refere o ingresso
     * @param string $status Identificador da situação dos ingressos a serem pesquisados
    */
    public function actionExportarCsvSemLote($evento='', $status='')
    {
        try {
            if (empty($evento) || empty($status)) {
                exit('Faltam informações para gerar o arquivo .csv do lote.');
            }
            $ingressos = (new ApiIngresso())->consultar([
                'id_agenda' => $evento,
                'status' => $status,
            ]);
            if ($ingressos->successo == '1') {
                header('Content-Type: text/csv; charset=utf-8');
                header('Content-Disposition: attachment; filename=lote_ingresso_' . date('d-m-Y_H-i-s') . '.csv');
                $output = fopen('php://output', 'w');
                fputcsv($output, ['Qrcode', 'Codigo', 'Nome do ocupante', 'Bloco', 'Fileira', 'Cadeira'], ';');
                foreach ($ingressos->objeto as $index => $ingresso) {
                    $infoProduto = !empty($ingresso->produto) ? explode(' ', $ingresso->produto) : [];
                    fputcsv($output, [
                        isset($ingresso->qrcode) && !empty($ingresso->qrcode) ? $ingresso->qrcode : '-', 
                        isset($ingresso->codigo) && !empty($ingresso->codigo) ? $ingresso->codigo : '-', 
                        isset($ingresso->ocupante_nome) && !empty($ingresso->ocupante_nome) ? utf8_decode($ingresso->ocupante_nome) : '-', 
                        isset($infoProduto[3]) && !empty($infoProduto[3]) ? $infoProduto[3] : '-', 
                        isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 0, 1) : '-', 
                        isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 1, strlen($infoProduto[1])) : '-'
                    ], ';');
                }
                die();
            }
            exit('Não há ingressos disponíveis para as informações fornecidas.');
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro - Geração de arquivo .csv', 'message' => $e->getMessage()]);
        }
    }
    
    /**
     * Mudar status de lote para "em Produção"
     */

protected/modules/admin/views/grafica/lote-estadio.php
<?php
use yii\helpers\Url;
use app\modules\admin\assets\GraficaAsset;

GraficaAsset::register($this);

$this->title = 'ADM Estádio Mineirão :: Lote "enviado ao Estádio"';
?>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h2 class="tituloGeral"><i class="fa fa-clone"></i> Lote "enviado ao Estádio"</h2>  
        </div>
        <div class="col-xs-4">
            <form name="form-estadio" method="post" action="<?= Url::to(['grafica/lote-estadio']); ?>">
                <label for="estadio_evento">Eventos</label>
                <select name="estadio_evento">
                    <?php foreach($eventos as $index => $evento) { ?>
                    <option value="<?= $evento->codigo ; ?>"<?= isset($codigo_evento) && $codigo_evento == $evento->codigo ? ' selected' : ''; ?>><?= $evento->nome; ?></option>
                    <?php } ?>
                </select>
                <input type="submit" class="btn btn-primary" value='Lotes de ingresso "em Produção"'>
            </form>
        </div>
    </div>
    
    <hr style="margin-top: 10px;">
    
    <?php if (isset($lotes) && !empty($lotes)) { ?>
    <input type="hidden" id="url-lote-estadio" value="<?= Url::to(['grafica/lote-estadio']); ?>">
    <input type="hidden" id="url-status-estadio" value="<?= Url::to(['grafica/status-lote-estadio']); ?>">
    <table class="table table-responsive table-striped table-bordered">
    <thead class="table-active">
        <tr>
            <th colspan="4" scope="col" class="aliCentro">Lotes disponíveis para este evento</th>
        </tr>
        <tr>
            <th scope="col" class="aliCentro">Lote Easy For Pay</th>
            <th scope="col" class="aliCentro">Total de ingressos do lote</th>
            <th scope="col" class="aliCentro">Data da produção</th>
            <th scope="col" class="aliCentro">Dados dos ingressos</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach($lotes as $key => $lote) { 
        $date1 = date_create(date('Y-m-d', strtotime($lote['data'])));
        $date2 = date_create(date('Y-m-d', strtotime('now')));
        $diff = date_diff($date2, $date1);
    ?>
        <tr>
            <td><?= $key; ?></td>
            <td><?= $lote['total']; ?></td>
            <td><?= date('d/m/Y H:i', strtotime($lote['data'])) . ' (<span class="' . ($diff->days > 5 ? 'plus-red' : 'plus-green') . '">' . $diff->days . ' dias</span>)'; ?></td>
            <td class="aliCentro"><a href="javascript:;" class="ver-ingresso" id="<?= $key; ?>">Mostrar</a></td>
        </tr>
        <tr id="ingressos-<?= $key; ?>" class="hidden">
            <td colspan="3">
                <table class="table table-responsive table-striped table-bordered">
                    <thead>
                        <th scope="col" class="aliCentro table-info">Qrcode</th>
                        <th scope="col" class="aliCentro table-info">Nome do ocupante</th>
                        <th scope="col" class="aliCentro table-info">Bloco</th>
                        <th scope="col" class="aliCentro table-info">Fileira</th>
                        <th scope="col" class="aliCentro table-info">Cadeira</th>
                    </thead>
                    <tbody>
                    <?php 
                    foreach($ingressos->objeto as $index => $ingresso) { 
                        if ($ingresso->lote_reserva == $key) { 
                            $infoProduto = explode(' ', $ingresso->produto);
                    ?>
                    <tr>
                        <td><?= isset($ingresso->qrcode) ? $ingresso->qrcode : '-'; ?></td>
                        <td><?= isset($ingresso->ocupante_nome) ? $ingresso->ocupante_nome : '-'; ?></td>
                        <td><?= isset($infoProduto[3]) && !empty($infoProduto[3]) ? $infoProduto[3] : '-'; ?></td>
                        <td><?= isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 0, 1) : '-'; ?></td>
                        <td><?= isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 1, strlen($infoProduto[1])) : '-'; ?></td>
                    </tr>
                    <?php 
                        }
                    } 
                    ?>
                    <tr>
                        <td class="aliCentro" colspan="3">
                            <a href="<?= Url::to(['grafica/exportar-csv', 'lote' => $key, 'evento' => $codigo_evento, 'status' => 'P']); ?>" class="btn btn-primary">Gerar arquivo .csv</a><br>
                        </td>
                        <td colspan="3" align="center">
                            <label for="lote-grafica">Lote da gráfica:</label>
                            <input type="text" id="lote-grafica-<?= $key; ?>" name="lote_grafica" value=""><br>
                            <button class="btn btn-primary btn-estadio" data-lote="<?= $key; ?>" data-evento="<?= isset($codigo_evento) ? $codigo_evento : ''; ?>">Registrar lote como "enviado ao Estádio"</button>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>    
    <?php } ?>
    </tbody>
    </table>
    <?php } else if ($codigo_evento > 0 && empty($lote)){ ?> 
    <div class="row">
        <label>Não há ingressos disponíveis com estas condições.</label>
    </div>
    <?php } ?>
</div>

protected/modules/admin/views/grafica/lote-producao.php
<?php
use yii\helpers\Url;
use app\modules\admin\assets\GraficaAsset;

GraficaAsset::register($this);

$this->title = 'ADM Estádio Mineirão :: Lote "em Produção"';
?>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h2 class="tituloGeral"><i class="fa fa-clone"></i> Lote "em Produção"</h2>  
        </div>
        <div class="col-xs-4">
            <form name="form-producao" method="post" action="<?= Url::to(['grafica/lote-producao']); ?>">
                <label for="producao_evento">Eventos</label>
                <select name="producao_evento">
                    <?php foreach($eventos as $index => $evento) { ?>
                    <option value="<?= $evento->codigo ; ?>"<?= isset($codigo_evento) && $codigo_evento == $evento->codigo ? ' selected' : ''; ?>><?= $evento->nome; ?></option>
                    <?php } ?>
                </select>
                <input type="submit" class="btn btn-primary" value="Lotes de ingresso reservados">
            </form>
        </div>
    </div>
    
    <hr style="margin-top: 10px;">
    
    <?php if (isset($lotes) && !empty($lotes)) { ?>
    <input type="hidden" id="url-lote-producao" value="<?= Url::to(['grafica/lote-producao']); ?>">
    <input type="hidden" id="url-status" value="<?= Url::to(['grafica/status-lote-producao']); ?>">
    <table class="table table-responsive table-striped table-bordered">
    <thead class="table-active">
        <tr>
            <th colspan="4" scope="col" class="aliCentro">Lotes disponíveis para este evento</th>
        </tr>
        <tr>
            <th scope="col" class="aliCentro">Lote Easy For Pay</th>
            <th scope="col" class="aliCentro">Total de ingressos do lote</th>
            <th scope="col" class="aliCentro">Data da reserva</th>
            <th scope="col" class="aliCentro">Dados dos ingressos</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach($lotes as $key => $lote) { 
        $date1 = date_create(date('Y-m-d', strtotime($lote['data'])));
        $date2 = date_create(date('Y-m-d', strtotime('now')));
        $diff = date_diff($date2, $date1);
    ?>
        <tr>
            <td><?= $key; ?></td>
            <td><?= $lote['total']; ?></td>
            <td><?= date('d/m/Y H:i', strtotime($lote['data'])) . ' (<span class="' . ($diff->days > 5 ? 'plus-red' : 'plus-green') . '">' . $diff->days . ' dias</span>)'; ?></td>
            <td class="aliCentro"><a href="javascript:;" class="ver-ingresso" id="<?= $key; ?>">Mostrar</a></td>
        </tr>
        <tr id="ingressos-<?= $key; ?>" class="hidden">
            <td colspan="3">
                <table class="table table-responsive table-striped table-bordered">
                    <thead>
                        <th scope="col" class="aliCentro table-info">Qrcode</th>
                        <th scope="col" class="aliCentro table-info">Nome do ocupante</th>
                        <th scope="col" class="aliCentro table-info">Bloco</th>
                        <th scope="col" class="aliCentro table-info">Fileira</th>
                        <th scope="col" class="aliCentro table-info">Cadeira</th>
                    </thead>
                    <tbody>
                    <?php 
                    foreach($ingressos->objeto as $index => $ingresso) { 
                        if ($ingresso->lote_reserva == $key) { 
                            $infoProduto = explode(' ', $ingresso->produto);
                    ?>
                    <tr>
                        <td><?= isset($ingresso->qrcode) ? $ingresso->qrcode : '-'; ?></td>
                        <td><?= isset($ingresso->ocupante_nome) ? $ingresso->ocupante_nome : '-'; ?></td>
                        <td><?= isset($infoProduto[3]) && !empty($infoProduto[3]) ? $infoProduto[3] : '-'; ?></td>
                        <td><?= isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 0, 1) : '-'; ?></td>
                        <td><?= isset($infoProduto[1]) && !empty($infoProduto[1]) ? substr($infoProduto[1], 1, strlen($infoProduto[1])) : '-'; ?></td>
                    </tr>
                    <?php 
                        }
                    } 
                    ?>
                    <tr>
                        <td class="aliCentro" colspan="6">
                            <a href="<?= Url::to(['grafica/exportar-csv', 'lote' => $key, 'evento' => $codigo_evento, 'status' => 'R']); ?>" class="btn btn-primary">Gerar arquivo .csv para impressão de ingressos</a>
                            <button class="btn btn-primary btn-producao" data-lote="<?= $key; ?>" data-evento="<?= isset($codigo_evento) ? $codigo_evento : ''; ?>">Registrar lote como "em Produção"</button>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>    
    <?php } ?>
    </tbody>
    </table>
    <?php } else if ($codigo_evento > 0 && empty($lote)){ ?> 
    <div class="row">
        <label>Não há ingressos disponíveis com estas condições.</label>
    </div>
    <?php } ?>
</div>

protected/modules/admin/views/grafica/lote-reservar.php
<?php
use app\modules\admin\assets\GraficaAsset;

GraficaAsset::register($this);
use yii\widgets\ActiveForm;

$this->title = 'ADM Estádio Mineirão :: Reservar lote';

$codigoMaior = 0;
if (isset($vendas) && !empty($vendas) && !empty($vendas->objeto)) {
    foreach ($vendas->objeto as $index => $venda) {
        if ($venda->vendas->status == 'Autorizado' && $venda->vendas->codigo > $codigoMaior) {
            $codigoMaior = $venda->vendas->codigo;
        }
    }
}
?>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h2 class="tituloGeral"><i class="fa fa-clone"></i> Reservar lote</h2> 
            <?php if ($retorno != '') {?>
                <p class="alert alert-<?= $retorno['tipo']; ?>"><?= $retorno['msg']; ?></p>
            <?php }?>
        </div>
        <div class="col-xs-4">
            <?php $form = ActiveForm::begin(['options'=>['class'=>'form form-horizontal']]);?>
            <label for="idEvento">Eventos</label>
            <select class="form-control" name="idEvento">
                <?php foreach($eventos as $index => $evento) { ?>
                <option value="<?= $evento->codigo ; ?>"<?= isset($codigo_evento) && $codigo_evento == $evento->codigo ? ' selected' : ''; ?>><?= $evento->nome; ?></option>
                <?php } ?>
            </select>
            <button type="submit" class="btn btn-success btn-evento"><i class="fa fa-check"></i> Buscar</button>
            <?php if (!empty($vendas) && !empty($vendas->objeto)) { ?>
            <label for="codigoCompra">Código de corte (venda)</label>
            <input class="form-control" name="codigoCompra" value="<?= $codigoMaior; ?>" /><br />
            <p><input type="submit" class="btn btn-primary" value="Reservar" /></p>
            <?php } ?>
            <?php ActiveForm::end();?>
        </div>
        <?php if (isset($vendas) && !empty($vendas) && !empty($vendas->objeto)) { ?>
        <div class="col-xs-8">
            <div class="col-xs-12 lote-reserva">
                <table class="uppercase table table-responsive table-striped">
                    <thead>
                        <tr>
                            <th colspan="5" scope="col" class="aliCentro">Vendas autorizadas após último corte (<?= !empty($ultimo_corte) ? $ultimo_corte : '-' ?>)</th>
                        </tr>
                        <tr>
                            <th>Identificador</th>
                            <th>Data</th>
                            <th>Total</th>
                            <th>Nome</th>
                            <th>Documento</th>
                        </tr>
                    </thead>
                    <tbody> 
            <?php
            foreach($vendas->objeto as $index => $venda) { 
                if ($venda->vendas->status == 'Autorizado') {
            ?>
                        <tr>
                            <td><?= $venda->vendas->codigo; if($venda->vendas->tipo == 'Taxa - 2ª via cartão mifare') echo ' <small>2ª via de cartão</small>'?></td>
                            <td><?= $venda->vendas->data; ?></td>
                            <td><?= 'R$ ' . number_format($venda->vendas->total, 2, ',', '.'); ?></td>
                            <td><?= $venda->vendas->comprador->nome; ?></td>
                            <td><?= $venda->vendas->comprador->documento; ?></td>
                        </tr>                    
            <?php
                }
            } 
            ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php } else if (!empty($ultimo_corte)) { ?>
        <div class="col-xs-8">
            Não há registros para a opção escolhida.
        </div>
        <?php } ?>
    </div>
    <hr style="margin-top: 10px;">   
</div>