protected/modules/admin/controllers/VendaController.php
<?php
namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\controllers\AbstractController;
use app\models\Agenda;
use app\models\Cliente;
use app\models\Produto;
use app\models\Mapa;
use app\models\Cupom;
use app\widgets\Ingresso;
use yii\web\Response;
use app\models\VendaBilheteria;
use app\widgets\Filipeta;
use app\models\Caixa;
use app\models\Cobranca;
use app\models\CarrinhoBilheteria;
use app\models\Ocupante;

/**
 * Controle para vendas
 */
class VendaController extends AbstractController
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $model = new VendaBilheteria;
        $model->scenario = 'iniciar-pedido';

        return $this->render('index', [
            'model' => $model
        ]);
    }

    public function actionIniciaPedido()
    {        
        $model = new VendaBilheteria;
        $model->scenario = 'iniciar-pedido';
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->post()) {
            $post = Yii::$app->request->post();
            $model->load($post);
            if($model->validate()) {
                return $model->geraParcelas(1,1);                
            }
            return (object) ['successo'=>'0', 'message'=>'Valor inválido.'];
        }        
    }

    /**
     * Página de venda de ingressos
     */
    public function actionIngressos () 
    {
        $session = $this->_sessionOpen();
        $objApiCliente = new Cliente;
        $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
        $agenda = new Agenda($objApiCliente);
        $agenda->listaTodosEventos();
        $datasEventos = $agenda->listaDatasEventos('MATRIZ');
        $mapa = '';
        $cupom = new Cupom($objApiCliente);
        $modelVnB = new VendaBilheteria;
        $modelVnB->scenario = 'iniciar-pedido';
        (new CarrinhoBilheteria($objApiCliente))->limparDaSessao();
        if (Yii::$app->request->post()) {
            $agendaData = explode('_', Yii::$app->request->post('Produto')['id_agenda']);
            $mapaModel = new Mapa();
            $mapa = $mapaModel->getMapa($agendaData[1]);
            $cupom->buscarCupom([
                'id' => 'PUB_' . Yii::$app->request->post('Produto')['id_agenda'] . '_%',
                'ativo' => '1'
            ]);
            
        }
        $apiCaixa = new Caixa();
        $caixa = $apiCaixa->resumoCaixa(['id' => 'caixa_' . Yii::$app->user->identity->cod_operador]);
        $render= isset($mapaModel) && $mapaModel->getAssentos() == 'livre' ? 'ingressos-sn' : 'ingressos';
        return $this->render($render, [
            'model' => new Produto($objApiCliente),
            'modelVnB' => $modelVnB,
            'mapa' => $mapa,
            'eventos' => $datasEventos,
            'id_agenda' => isset(Yii::$app->request->post('Produto')['id_agenda']) ? Yii::$app->request->post('Produto')['id_agenda'] : '',
            'carrinho' => (new CarrinhoBilheteria($objApiCliente))->consultarCarrinho(),
            'cupons' => isset($cupom->lista) && !empty($cupom->lista) ? $cupom->lista : $cupom,
            'caixa' => $caixa
        ]);
    }
    
    /**
     * Montar select de ingresso, usando o widget correspondente
     * @return string
     */
    public function actionSelectIngresso()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
            $session = $this->_sessionOpen();
            $objApiCliente = new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            $post = Yii::$app->request->post();
            $produto = new Produto($objApiCliente);
            $produto->codigo = $post['produto_codigo'];
            $produto->buscarProduto();
            $cupom = new Cupom($objApiCliente);
            $cupom->buscarCupom([
                'id' => 'PUB_' . $post['id_agenda'] . '_%',
                'ativo' => '1'
            ]);
            return (object)['successo' => '1', 'select' => Ingresso::getSelectTipo($produto, $cupom->lista, $post['index'], '', false)];
        }
        return (object)['successo' => '0', 'erro' => ['mensagem' => 'Faltam parâmetros para montar o select de ingresso']];
    }

    public function actionFilipeta()
    {
        try {
            if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $post=Yii::$app->request->post();
                $compra=isset($post['objeto']['compra']) ? $post['objeto']['compra'] : $post['compra'];
                $filipeta = Filipeta::geraExibicao($compra);
                return (object)['successo'=>'1', 'html'=>$filipeta];
            }
        } catch (Exception $e) {
            return json_encode(['successo'=>'0']);
            $this->render('error', ['name' => 'Erro ao gerar a filipeta', 'message' => $e->getMessage()]);
        }         
    }
    
    /**
     * Adicionar produto ao carrinho de compras - Bilheteria
     * Formato do Post: [produto]: {'codigo': '', 'unidades': ''}
     */
    public function actionAdicionarProdutoCarrinho () 
    {
        try {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
                $session = Yii::$app->session;
                $session->open();
                $objApiCliente = new Cliente;
                $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
                $produtos = new Produto($objApiCliente);  
                $produtos->codigo = Yii::$app->request->post()['produto_codigo'];
                $produtos->buscarProduto();
                $session->set('documento_unidade', $produtos->vendedor->documento);
                return (new CarrinhoBilheteria($objApiCliente))->atualizarCarrinho(Yii::$app->request->post());
            }
            return (object)['successo' => '0', 'erro' => ['mensagem' => 'Faltam parâmetros para adicionar produto ao carrinho - bilheteria.']];
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro ao adicionar produto ao carrinho - bilheteria', 'message' => $e->getMessage()]);
        }
    }
    
    /**
     * Remover produto do carrinho de compras e da sessão - Bilheteria
     */
    public function actionRemoverProdutoCarrinho () 
    {
        try {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
                $session = Yii::$app->session;
                $session->open();
                $objApiCliente = new Cliente;
                $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
                return (new CarrinhoBilheteria($objApiCliente))->atualizarCarrinho([
                    'produto_codigo' => Yii::$app->request->post()['produto_codigo'], 
                    'produto_unidades' => Yii::$app->request->post()['produto_unidades']
                ]);
            }
            return (object)['successo' => '0', 'erro' => ['mensagem' => 'Faltam parâmetros para adicionar produto ao carrinho - bilheteria.']];
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro ao remover produto do carrinho - bilheteria', 'message' => $e->getMessage()]);
        }
    }
    
    /**
     * Adicionar cupom ao carrinho de compras - Bilheteria
     * Formato do Post: [cupom]: {'id': '', 'unidades': ''}
     */
    public function actionAdicionarCupomCarrinho () 
    {
        try {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
                $session = Yii::$app->session;
                $session->open();
                $objApiCliente = new Cliente;
                $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
                $post = Yii::$app->request->post();
                $return = true;
                $returnApi = (new CarrinhoBilheteria($objApiCliente))->atualizarCarrinho($post, (boolean)$post['assentos']);
                if ($returnApi->successo == '0') {
                    $return = false;
                }
                return $return ? (object)['successo' => '1'] : (object)['successo' => '0', 'erro' => ['mensagem' => 'Falha ao adicionar cupom ao carrinho - bilheteria.']];
            }
            return (object)['successo' => '0', 'erro' => ['mensagem' => 'Faltam parâmetros para adicionar cupom ao carrinho - bilheteria.']];
        } catch (Exception $e) {
            return $this->render('error', ['name' => 'Erro ao adicionar cupom ao carrinho - bilheteria', 'message' => $e->getMessage()]);
        }
    }
    
    /**
     * Remover cupom do carrinho de compras - Bilheteria
     */
    public function actionRemoverCupomCarrinho ()
    {
        try {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
                $session = Yii::$app->session;
                $session->open();
                $objApiCliente = new Cliente;
                $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
                return (new CarrinhoBilheteria($objApiCliente))->removerCupomCarrinho(Yii::$app->request->post('Ocupante'), (boolean)Yii::$app->request->post()['assentos']);
            }
            return (object)['successo' => '0', 'erro' => ['mensagem' => 'Faltam parâmetros para remover cupom do carrinho - bilheteria.']];
        } catch (Exception $e) {

protected/modules/admin/views/bilheteria/ativar.php
 <?php
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use app\modules\admin\assets\BilheteriaAsset;

BilheteriaAsset::register($this);
$this->title = 'ADM Estádio Mineirão :: Ativar ingresso';
$todosAtivos = true;

$form = ActiveForm::begin([
    'id' => 'form-ativar-ingresso',
]);
?>
<div class="container">
    
    <input type="hidden" id="url-check-venda" value="<?= Url::to(['/admin/bilheteria/check-venda']); ?>">
    <input type="hidden" id="url-check-carrinho" value="<?= Url::to(['/admin/bilheteria/check-carrinho']); ?>">
    <input type="hidden" id="url-ativar-ingresso" value="<?= Url::to(['/admin/bilheteria/ativar-ingresso']); ?>">
    
    <div class="row">
        <h2 class="tituloGeral"><i class="fa fa-clone"></i> Ativar ingresso - Temporada Mineirão Tribuna e Embaixada</h2>
    </div>

    <div id="localizar" class="row boxLer">
        <div class="ingresso col-md-6">
            <h3><?= $radioList[0] ?></h3>
            <?= $form->field($model, 'qrcode_voucher')->textInput(['id' => 'qrcode_voucher', 'tabindex' => '2', 'autofocus'=>'autofocus']); ?>
        </div>
        <div class="ingresso col-md-6">
            <h3><?= $radioList[1] ?></h3>
            <?= $form->field($model, 'documento')->textInput(['disabled' => true, 'id' => 'documento', 'tabindex' => '4']); ?>
        </div>
        <div class="col-md-12">
            <button type="submit" id="ativar-ingresso" class="btn btn-success"><i class="fa fa-check"></i> Buscar</button>                            
        </div>    
    </div>
    
    <br><hr class="bordaPont">
<?php ActiveForm::end(); ?>
    
    <div class="row">
        <div class="col-md-12" id="data-venda">
<?php
if (isset($resultadoBusca) && count($resultadoBusca) > 0) {
    foreach ($resultadoBusca as $venda) {
        if (isset($venda['objeto'])) {
?>
            <div class="row zeraesp tableResumo">
                <div class="col-xs-12" style="background:#ddd; padding-top:10px; padding-bottom:10px;">
                    <div class="col-xs-4 zeraesp text10">
                        <div class="col-md-3 zeraesp tableResumoBold">Comprador: </div>
                        <div class="col-md-9 zeraesp"><?= $venda['objeto']->vendas->comprador->nome ?></div>
                        <div class="col-md-3 zeraesp tableResumoBold">Documento: </div>
                        <div class="col-md-9 zeraesp"><?= $venda['objeto']->vendas->comprador->documento ?></div>
                        <div class="col-md-3 zeraesp tableResumoBold">Identificador: </div>
                        <div class="col-md-9 zeraesp"><?= $venda['objeto']->vendas->codigo ?></div>
                    </div>
                    <div class="col-xs-4 zeraesp text10">
                        <div class="col-md-3 tableResumoBold">Data: </div>
                        <div class="col-md-9"><?= $venda['objeto']->vendas->data ?></div>
                        <div class="col-md-3 tableResumoBold">Status: </div>
                        <div class="col-md-9<?= ($venda['objeto']->vendas->status == 'Autorizado' ? ' plus-green' : ' plus-red') ?>">
                            <?= $venda['objeto']->vendas->status; ?>
                        </div>
                        <div class="col-md-3 tableResumoBold">Total: </div>
                        <div class="col-md-9">R$ <?= number_format($venda['objeto']->vendas->valor, 2, ',', '.') ?></div>
                    </div>
                    <div class="col-xs-4 zeraesp text10 text-right">
                        <button type="button" class="btn btn-default btn-lg imprimir" onclick="window.open('<?= Url::to(['/admin/bilheteria/filipetas']); ?>?tipo=venda&codigo=<?= $venda['objeto']->vendas->codigo; ?>', 'filipeta', 'width=550,height=350,toolbar=no,scrollbars=no,location=no')">
                            <span class="glyphicon glyphicon-print"></span> Imprimir filipetas de todos
                        </button>
                    </div>
                </div>
            <?php 
            if (isset($venda['detalhes']) && count($venda['detalhes']>0)) {
                foreach ($venda['detalhes'] as $detalhe) { 
            ?>
                <div class="col-md-12">

                    <div class="tracejado">
                        <div class="col-xs-2" style="padding-left:0px;">
                            <?=$detalhe['evento']['nome'].' '.$model->documento?><br />
                            <img alt="<?= $detalhe['evento']['nome']?>" src="<?= $detalhe['evento']['banner']?>">
                        </div>

                        <div class="col-xs-2">
                            <?= $detalhe['produto']->nome ?><br>
                            <?= number_format($detalhe['produto']->unidades, 0)?> unidade <?= $detalhe['produto']->unidades > 1 ? 's' : ''?><br>

                            <?php
                            if($detalhe['produto']->valor!=''){
                                if ($detalhe['produto']->desconto->fixo > 0 || $detalhe['produto']->desconto->percentual > 0) { ?>
                                <span class="strikeDesconto">
                                R$ <?= number_format($detalhe['produto']->valor, 2, ',', '.') ?>
                                </span><br>
                                R$ <?= $detalhe['produto']->desconto->percentual > 0 
                                    ? number_format(floatval($detalhe['produto']->valor) - (floatval($detalhe['produto']->valor) * floatval($detalhe['produto']->desconto->percentual)), 2, ',' . '.') 
                                    : number_format($detalhe['produto']->valor - $detalhe['produto']->desconto->fixo, 2, ',', '.'); ?>
                                
                                <?php } else {?>
                                R$ <?= number_format($detalhe['produto']->valor, 2, ',', '.');
                                }
                            } ?>                                   
                        </div>
                        
                        <div class="col-xs-3">
                            Nome:<br>
                            <span><?= isset($detalhe['mineiraoCard']->nome->valor) ? $detalhe['mineiraoCard']->nome->valor : '' ?></span>
                        </div>
                        
                        <div class="col-xs-2">
                            Documento:<br>
                            <span><?= isset($detalhe['mineiraoCard']->doc->valor) ? $detalhe['mineiraoCard']->doc->valor : '' ?></span>
                        </div>
                        
                        <div class="col-xs-3 zeraesp text-right">
                    <?php
                    if (isset($detalhe['mineiraoCard']->doc->valor)) {
                        $docClienteVoucher = $model->localizar == 1 ? $venda['voucher'][2] : $model->documento;
                        $btnIngresso = $model->botaoIngresso($venda['objeto']->vendas->codigo, strtolower($docClienteVoucher), strtolower($venda['objeto']->vendas->comprador->documento), strtolower($detalhe['mineiraoCard']->doc->valor), $detalhe['evento']['id']);
                        $todosAtivos = $btnIngresso['ativo'];
                    ?>
                            <button type="button" class="btn btn-default imprimir" onclick="window.open('<?= Url::to(['/admin/bilheteria/filipetas']); ?>?tipo=produto&codigo=<?= $venda['objeto']->vendas->codigo; ?>&produto=<?= $detalhe['produto']->codigo; ?>&documento=<?= $detalhe['mineiraoCard']->doc->valor; ?>', 'filipeta', 'width=550,height=350,toolbar=no,scrollbars=no,location=no')">
                                <span class="glyphicon glyphicon-print"></span> Imprimir filipeta
                            </button>
                        <?php 
                        if ($btnIngresso['mostrar'] && $venda['objeto']->vendas->status == 'Autorizado') { ?>
                            <button type="button" id="salvar-<?= $detalhe['produto']->codigo; ?>" rel="<?= $detalhe['mineiraoCard']->doc->valor; ?>" class="salvar-ingresso btn-lg btn-success modal-ingresso" data-toggle="modal">INGRESSO</button>
                            <?php Modal::begin([
                                'header' => '<h4 align="center">Ingresso</h4>',
                                'size'   => 'modal-sm',
                                'id'     => 'modal-' . $detalhe['produto']->codigo,
                                'options'=> [
                                    'class' => 'modal-center'
                                ]
                            ]); ?>
                            <?= $this->render('salvar-form',[
                                'id_agenda' => $detalhe['evento']['id'],
                                'id_carrinho_produto' => $detalhe['produto']->id_carrinho,
                                'id_carrinho_id' => $detalhe['mineiraoCard']->doc->id_carrinho,
                                'qrcode_check' => $btnIngresso['qrcode'],
                                'venda' => $venda,
                                'detalhe' => $detalhe,
                                'id' => 'form-ingresso-' . $detalhe['produto']->codigo,
                                'hidden' => true,
                                'status' => isset($btnIngresso['status']) ? $btnIngresso['status'] : '',
                                'ocupante_nome' => $detalhe['mineiraoCard']->nome->valor,
                                'ocupante_documento' => $detalhe['mineiraoCard']->doc->valor
                            ]); ?>
                            <?php Modal::end(); ?>
                        <?php } ?>
                            <p class="text-center alert alert-<?= $btnIngresso['tipo']; ?> msg-<?= $detalhe['produto']->codigo; ?>"><?= $btnIngresso['msg']; ?></p>
                    <?php } ?>
                        </div>
                    </div>
                </div>
                <?php }
            } ?>
            </div>
            <hr>
        <?php 
        } else {
            echo '<p>Não há compra para as informações fornecidas.</p>';
        }
    }
} else { ?>
    <div class="alert alert-warning">Escolha um dos campos acima e forneça as informações para busca.</div>
<?php } ?>
        </div>
    </div>
    
    <div class="col-md-12<?= (count($resultadoBusca) > 0 && $todosAtivos) ? '' : ' hidden';?>" id="div-next">
        <button type="button" id="btn-restart" class="btn btn-success"><i class="fa fa-check"></i> Próximo cliente</button>                            
    </div> 
    
</div>

<!-- Modal - Mensagens -->
<?php Modal::begin([
    'header' => '<h4 align="center">Atenção</h4>',
    'size'   => 'modal-sm',
    'id'     => 'modal-mensagem',
    'options'=> [
        'class' => 'modal-center'
    ],
    'clientOptions' => [
        'keyboard' => false,
        'backdrop' => 'static',
    ]
]);
Modal::end(); ?>

protected/modules/admin/views/bilheteria/filipetas.php
<?php
use yii\helpers\Html;

$count = -1;
$tagControl = 0;
$tagOcupante = [];
$ocupantes = [];
if (isset($produtos->tags) && !empty($produtos->tags)) {
    foreach ($produtos->tags as $tag) {
        $arrTag = isset($tag->nome) ? explode('_', $tag->nome) : explode('_', $tag->documento);
        if ($tagControl != $arrTag[0]) {
            $count ++;
            $tagControl = $arrTag[0];
            $tagOcupante[$count]['produto'] = $tagControl;
        }
        $tagOcupante[$count][$arrTag[1]] = $tag->valor;
    }
    foreach($tagOcupante as $index => $ocupante) {
        $ocupantes[$ocupante['produto']] = $ocupante;
    }
}
?>
<page size="filipetas">
    <?php 
    foreach($produtos->produtos as $index => $produto) { 
        if ($tipo == 'venda' || ($tipo == 'produto' && $produtoCodigo == $produto->codigo)) {
    ?>
    <div class="filipeta filipeta-<?= $produto->codigo ?>">
        <?= Html::img('@web/images/logoMineirap.png', ['style' => 'width:130px']); ?>
        <hr style="border:2px groove #000; margin:5px 0px;">
        <p style="font-size:19px;"><strong><?= $evento->objeto[0]->nome; ?></strong></p> 
        <p style="font-size:19px;"><strong><?= $ocupantes[$produto->codigo]['nome']; ?> (Documento: <?= $ocupantes[$produto->codigo]['documento']; ?>) </strong></p>
        <p><strong><?= $produto->nome ?></strong></p>
        <!--<p>Portão A</p>-->
        <p>Nº do seguro: 409876 - Mapfre Seguros</p>
        <hr style="border:2px groove #aaa; margin:5px 0px;">
        <p style="font-size:11px;">Seja bem vindo ao gigante! Esta filipeta faz parte do seu ingresso com informações do seu assento.<br>Estádio Mineirão - www.estadiomineirao.com.br</p>
        <hr style="border:2px groove #000; margin:5px 0px;">
    </div>
    <?php 
        }
    } 
    ?>
</page>

protected/modules/admin/views/bilheteria/imprimir.php
<?php
print $filipeta;

protected/modules/admin/views/bilheteria/validar-entrada.php
<?php 
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\assets\VendaAsset;
use yii\helpers\Url;

VendaAsset::register($this);
?>

<div class="ajustaRodape">
	<h1><span style="font-weight:200;">Ingressos</span> - Consulta ingresso avulso</h1>
	<input type="hidden" id="url-filipeta" value="<?= Url::to(['venda/filipeta']); ?>">
	<?php if(Yii::$app->session->hasFlash('sucesso')) {?>
		<p class="alert alert-success"><?=Yii::$app->session->getFlash('sucesso')?></p>
	<?php }?>
	<?php $formA= ActiveForm::begin(['id'=>'consultar-qrcode-form', 'class'=>'col-sm-12']) ?>
	<div class="row">
		<div class="col-sm-12 semPad">
			<?= $formA->field($model, 'idEvento')->dropDownList(ArrayHelper::map($eventos, 'id', 'data', 'evento'))->label('Selecione o evento') ?>
		</div>
		<div class="col-sm-6" style="padding-left:0px;">
			<?= $formA->field($model, 'qrcode')->label('Leia o QR Code') ?>
		</div>
		<div class="col-sm-6" style="padding-right:0px;">
			<?= $formA->field($model, 'documento')->label('Digite o documento') ?>
		</div>
	</div>
	<div class="form-group" style="text-align:center;">
		<?= Html::submitButton('Consultar', ['class' => 'btn btn-primary btn-pagar']) ?>
	</div>
	<?php ActiveForm::end() ?>


	<?php if(is_array($model->lista) && count($model->lista)>0) {
		//coloca em ordem reversa (recente p/ antigo)
		$lista=array_reverse($model->lista)?>
		<hr>
		<div class="col-sm-12"><h3 class="aliCentro">Revise as informações abaixo para validar a entrada</h3></div><br clear="all"><br>
		<?php foreach($lista as $m){?>
			<div class="col-sm-4">
				<p><strong>Evento:</strong> <?=$m->objIngresso->agenda->nome?> - <?=$m->objIngresso->agenda->data?></p>
				<p><strong>Comprador:</strong> <?=$m->objIngresso->comprador?> - <?=$m->objIngresso->comprador_documento?></p>
				
			</div>	
			<div class="col-sm-5">
				<h4><?=$m->objIngresso->produto?></h4>
				<p><strong>Ocupante deste ingresso:</strong> <?=$m->objIngresso->ocupante_nome?> - <?=$m->objIngresso->documento?></p>				
				
			</div>
			<div class="col-sm-3">
				<div class="col-sm-6 aliCentro">
					<?php  if($m->objIngresso->utilizacoes==0){?>					
						<?php $formB= ActiveForm::begin(['id'=>'validar-entrada-form', 'action'=>'validar-ingresso', 'class'=>'col-sm-12']) ?>
						<?= Html::hiddenInput('id_agenda', $m->objIngresso->agenda->id) ?>
						<?= Html::hiddenInput('qrcode', $m->objIngresso->qrcode) ?>
						<?= Html::submitButton('VALIDAR', ['class' => 'botCircleIng font-awesome btn btn-primary', 'title'=>'Validar']) ?>
						<?php ActiveForm::end() ?>
					<?php }?>
				</div>
				<div class="col-sm-6 aliCentro">
					<?php if($m->objIngresso->utilizacoes==0){?>	
						<?= Html::button('Imprimir filipeta',['class'=>'botCircleIng2 font-awesome imprimir-filipeta btn btn-default','type'=>'button', 'data-compra'=>$m->objIngresso->compra->codigo]);?>
					<?php }?>
				</div>
			</div>
			<div class="col-sm-12">
				<?php if($m->objIngresso->utilizacoes>0){
					$dataObj=\DateTime::createFromFormat('Y-m-d H:i:s',$m->objIngresso->utilizacoes_ultima_data);?>
					<p class="alert alert-info">Este ingresso já foi utilizado em <?=$dataObj->format('d/m/Y H:i:s')?></p>
				<?php } ?>
			</div>
			<p class="clearfix"></p>
				<?php 
				if (count($m->objCompra->carrinho->produtos)>1) {
					$outrosProdutos=[];
					foreach ($m->objCompra->carrinho->produtos as $produto) {
						if($produto->codigo == $m->objIngresso->produto_codigo) continue;
						$outrosProdutos[]=$produto->nome;
							
					};
					if(count($outrosProdutos)>0){?>
						<div class="col-sm-12">
							<h5>Outros produtos desta compra:</h5>
							<p><?=implode('<br />',$outrosProdutos)?></p>
						</div>	
					<?php } 
				} ?>
				<p class="clearfix"></p>
				<hr />
		<?php }?>
	<?php }?>
</div>