protected/modules/admin/controllers/ProdutoController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\controllers\AbstractController;
use app\models\Produto;
use app\models\WsProduto;
use app\models\Tags;
use app\models\Anexos;
use yii\web\UploadedFile;
use yii\web\Response;
use app\models\Agenda;
use app\models\Cliente;
use app\models\Mapa;
use app\models\Carrinho;

/**
 * Controle de Produto
 */
class ProdutoController extends AbstractController
{
    
    /**
     * Renders the index view for the module
     * @param boolean $matriz Boolean indicando se é uma ação para matriz ou não
     * @return string
     */
    public function actionIndex($matriz=false)
    {
        $session = $this->_sessionOpen();
        $objApiCliente = new Cliente;
        $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));

        $model = new Produto($objApiCliente);        
        if (Yii::$app->request->post()) {
            $post = Yii::$app->request->post('Produto');
            $matriz = (boolean)$post['matriz'];
            if (isset($post['id_agenda']) && $post['id_agenda'] > 0) {
                $model->buscarProdutosFiltro(['id_agenda' => $post['id_agenda']], false);
            }
        }
        
        $agenda = new Agenda($objApiCliente);
        (boolean)($matriz) ? $agenda->buscarEventosPorFiltro(['nome' => 'MATRIZ%']) : $agenda->listaTodosEventos();
        $datasEventos = $agenda->listaDatasEventos($matriz == true ? '' : 'MATRIZ');
        return $this->render('index', [
            'produto' => $model,
            'eventos' => $datasEventos,
            'matriz' => $matriz
        ]); 
    }
    
    /**
     * Cadastro de novo produto
     */
    public function actionAssentos() 
    {
        $session = $this->_sessionOpen();
        $objApiCliente = new Cliente;
        $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
        
        $agenda = new Agenda($objApiCliente);
        $agenda->buscarEventosPorFiltro(['nome' => 'MATRIZ%']);
        $eventos = $agenda->getAgendaData();
        $datasEventos = $agenda->listaDatasEventos();
        
        $model = new Produto($objApiCliente);
        $model->buscarProdutosFiltro(['id_agenda' => implode(',', $eventos),
            'tags' => [
                ['nome' => 'tipo',  'valor' => 'matriz']
            ]
        ]);
        return $this->render('assentos', [
            'matrizes' => $model->lista,
            'model' => $model,
            'eventos' => $datasEventos,
            'tags' => new Tags
        ]);
    }
    
    /**
     * Cadastrar uma nova matriz e suas tags
     * @return type
     */
    public function actionNovaMatriz () 
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post('Produto'))) {
            $session = $this->_sessionOpen();
            $objApiCliente = new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            $produto = new Produto($objApiCliente);            
            if ($produto->checkTag(Yii::$app->request->post('Tags'), 'matriz')) {
                return (object)['successo' => '0', 'erro' => ['mensagem' => 'Já existe uma matriz com o identificador "' . Yii::$app->request->post('Tags')[1]['valor'] . '"']];
            }
            if ($produto->load(Yii::$app->request->post())) {
                $returnApi = $produto->criarProduto();
                if ($returnApi->successo == '1') {
                    return $produto->salvarTag(Yii::$app->request->post('Tags'), $returnApi->objeto->codigo);
                }
                return $returnApi;
            }
            return (object)['successo' => '0', 'erro' => ['mensagem' => 'Não foi possível cadastrar a matriz']];
        }
        return (object)['successo' => '0', 'erro' => ['mensagem' => 'Faltam parâmetros para cadastrar nova matriz.']];
    }
    
    /**
     * Dado um identificador de matriz, buscar os seus setores
     * @return Produto
     */
    public function actionSetor() 
    {
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            $session = $this->_sessionOpen();
            $objApiCliente=new Cliente;
            $objApiCliente->buscarUnidadePor('user_token', $session->get('token_unidade'));
            $model = new Produto($objApiCliente); 
            $model->buscarProdutosFiltro(['id_agenda' => $post['data_agenda'],
                'tags' => [
                    ['nome' => 'matriz',  'valor' => $post['matriz']],
                    ['nome' => 'tipo',  'valor' => 'setor']
                ]
            ]);
            return (object)['successo' => '1', 'setores' => $model];
        }
        return (new WsProduto)->getApiError('Faltam parâmetros para buscar os setores.');
    }
    
    /**
     * Cadastrar um novo setor e suas tags
     * @return type
     */
    public function actionNovoSetor () 
    {
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post('Produto'))) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $session = $this->_sessionOpen();
            $objApiCliente=new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            $produto = new Produto($objApiCliente); 
            if ($produto->checkTag(Yii::$app->request->post('Tags'))) {
                return (new WsProduto)->getApiError('Já existe um setor identificado como "' . Yii::$app->request->post('Tags')[2]['valor'] . '"');
            }
            if ($produto->load(Yii::$app->request->post())) {
                $returnApi = $produto->criarProduto();
                if ($returnApi->successo == '1') {
                    return $produto->salvarTag(Yii::$app->request->post('Tags'), $returnApi->objeto->codigo);
                }
                return $returnApi;
            }
            return (new WsProduto)->getApiError('Não foi possível cadastrar o setor');
        }
        return (new WsProduto)->getApiError('Faltam parâmetros para cadastrar novo setor.');
    }
    
    /**
     * Dado um identificador de matriz e um de setor, buscar as suas fileiras
     * @return Produto
     */
    public function actionFileira() 
    {
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            $session = $this->_sessionOpen();
            $objApiCliente=new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            $model = new Produto($objApiCliente); 
            $model->buscarProdutosFiltro(['id_agenda' => $post['data_agenda'],
                'tags' => [
                    ['nome' => 'matriz',  'valor' => $post['matriz']],
                    ['nome' => 'setor',  'valor' => $post['setor']],
                    ['nome' => 'tipo', 'valor' => 'fileira']
                ]
            ]);
            return (object)['successo' => '1', 'fileiras' => $model];
        }
        return (new WsProduto)->getApiError('Faltam parâmetros para buscar as fileiras.');
    }
    
    /**
     * Cadastrar um nova fileira e suas tags
     * @return type
     */
    public function actionNovaFileira() 
    {
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post('Produto'))) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $session = $this->_sessionOpen();
            $objApiCliente=new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            return (new Produto($objApiCliente))->criarFileira(Yii::$app->request->post());
        }
        return (new WsProduto)->getApiError('Faltam parâmetros para cadastrar novo setor.');
    }
    
    /**
     * Dado um identificador de matriz, um setor e uma fileira, carregar seus assentos
     */
    public function actionAssento()
    {
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            $session = $this->_sessionOpen();
            $objApiCliente=new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            $produto = new Produto($objApiCliente); 
            $produto->buscarProdutosFiltro(['id_agenda' => $post['data_agenda'],
                'tags' => [
                    ['nome' => 'matriz',  'valor' => $post['matriz']],
                    ['nome' => 'setor',  'valor' => $post['setor']],
                    ['nome' => 'fileira',  'valor' => $post['fileira']],
                    ['nome' => 'tipo', 'valor' => 'assento']
                ]
            ]);
            return (object)['successo' => '1', 'assentos' => $produto];
        }
        return (new WsProduto)->getApiError('Faltam parâmetros para buscar os assentos.');
    }
    
    /**
     * Dado um identificador de matriz, setor e fileira, registrar seus assentos
     */
    public function actionNovoAssento () 
    {
        if (Yii::$app->request->isAjax && !empty(Yii::$app->request->post('Produto'))) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $session = $this->_sessionOpen();
            $objApiCliente=new Cliente;
            $objApiCliente->buscarUnidadePor('user_token',$session->get('token_unidade'));
            return (new Produto($objApiCliente))->criarAssento(Yii::$app->request->post());
        }
        return (new WsProduto)->getApiError('Faltam parâmetros para cadastrar novo assento.');
    }
    
    /**
     * Editar uma matriz de assentos, definindo assentos especiais, preço, estoque, status, reservas

protected/modules/admin/views/produto/add-tag.php
<?php
$this->title = 'Produto - Tag';
?>
<h1><span style="font-weight:200;">Produto</span> - Tag</h1>
<h2><?=$produto->nome?></h2>
<p><?=$produto->descricao?></p>
<?= $this->render('/commons/form-tag',['model'=>$model])?>

protected/modules/admin/views/produto/alterar-estoque.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Produto - Estoque';
?>
<h1><span style="font-weight:200;">Produto</span> - Estoque</h1>
<h2><?=$produto->nome?></h2>
<p><?=$produto->descricao?></p>
<p>oferecido: <?=$produto->oferecido?><br />
vendido: <?=$produto->vendido?><br />
reservado: <?=$produto->reservado?><br />
disponivel: <?=$produto->disponivel?></p>

<?php
$form = ActiveForm::begin(['id' => 'produto-form']); ?>
<?= $form->field($produto, 'tipoMovimentoEstoque')->radioList(['adicionar'=>'Adicionar', 'remover'=>'Remover']) ?>
<?= $form->field($produto, 'unidadesEstoque', ['inputOptions'=>['class'=>'form-control', 'type'=>'number']]) ?>
<div class="form-group">
    <?= Html::submitButton('Salvar', ['class' => 'btn btn-primary']) ?>
</div>
<?php ActiveForm::end(); ?>

protected/modules/admin/views/produto/assentos.php
<?php
use yii\helpers\Url;
use app\models\Tags;
use app\assets\ProdutoAsset;

ProdutoAsset::register($this);

$this->title = 'Produtos - Matriz de assentos';
?>
<div class="content">
    <h1><span style="font-weight:200;">Produtos</span> - Matriz (assentos marcados)</h1>
    <input type="hidden" id="url-setor" value="<?= Url::to(['setor']); ?>">
    <input type="hidden" id="url-fileira" value="<?= Url::to(['fileira']); ?>">
    <input type="hidden" id="url-assento" value="<?= Url::to(['assento']); ?>">
    <input type="hidden" id="url-salvar-assentos" value="<?= Url::to(['salvar-assentos']); ?>">
    
    <div class="row">
        <div class="col-xs-2">
            1 - Matriz:
        </div>
        <div class="col-xs-6">
            <select id="matriz" style="width:100%;">
            <?php if (!empty($matrizes)) { ?>
                <option>Escolha uma matriz</option>
                <?php 
                foreach ($matrizes as $index => $matriz) { 
                    $tmpTag = (new Tags)->objetoTags($matriz->tags);
                ?>
                <option value="<?= $matriz->codigo; ?>" data-matriz="<?= $tmpTag->matriz; ?>" data-agenda="<?= $matriz->id_agenda; ?>"><?= $matriz->nome; ?></option>
                <?php }?>
            <?php } else { ?>
                <option>Cadastre matriz</option>
            <?php } ?>
            </select>
        </div>
        <div class="col-xs-4" style="text-align:center;">
            <input type="button" id="btn-matriz" class="btn btn-default" value="Cadastrar matriz" style="width:150px;">
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-2">
            2 - Setor:
        </div>
        <div class="col-xs-6">
            <select id="setor" style="width:100%;" disabled>
                <option>Escolha uma matriz</option>
            </select>
        </div>
        <div class="col-xs-4" style="text-align:center;">
            <input type="button" id="btn-setor" class="btn btn-default" value="Cadastrar setor" disabled style="width:150px;">
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-2">
            3 - Fileiras:
        </div>
        <div class="col-xs-6">
            <select id="fileira" style="width:100%;" disabled>
                <option>Escolha um setor</option>
            </select>
        </div>
        <div class="col-xs-4" style="text-align:center;">
            <input type="button" id="btn-fileiras" class="btn btn-default" value="Cadastrar fileiras" disabled style="width:150px;">
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-xs-2">
            4 - Assentos:
        </div>
        <div class="col-xs-6">
            <div class="row">
                <div class="col-xs-12" id="div-assentos"></div>
            </div>
        </div>
        <div class="col-xs-4" style="text-align:center;">
            <input type="button" id="btn-assentos" class="btn btn-default" value="Cadastrar assentos" disabled style="width:150px;">
        </div>
    </div>
</div>

<?= $this->render('modal-matriz', [
    'model' => $model,
    'eventos' => $eventos,
    'tags' => $tags
]); ?>

<?= $this->render('modal-setor', [
    'model' => $model,
    'tags' => $tags
]); ?>

<?= $this->render('modal-fileira', [
    'model' => $model,
    'tags' => $tags
]); ?>

<?= $this->render('modal-assentos', [
    'model' => $model,
    'tags' => $tags
]); ?>

<br>
<br>
<br>
<br>

protected/modules/admin/views/produto/criar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Produto - Cadastrar' . (isset($matriz) && $matriz == true ? ' (matriz)' : '');
?>

<div class="container">
	<div class="row">
		<h2 class="tituloGeral"><i class="fa fa-clone"></i> Produto - Cadastrar <?= isset($matriz) && $matriz == true ? ' (matriz)' : ''; ?></h2>
	</div>

	<?php
	$form = ActiveForm::begin(['id' => 'produto-form']); ?>

	<?= $form->field($model, 'id_agenda')->dropDownList(yii\helpers\ArrayHelper::map($eventos, 'id', 'data', 'evento')) ?>

	<?= $form->field($model, 'nome') ?>

	<?= $form->field($model, 'descricao')->textarea(['rows' =>5]) ?>

	<?= $form->field($model, 'valor') ?>

	<?= $form->field($model, 'descontoFixo') ?>

	<?= $form->field($model, 'descontoPercentual') ?>

	<?= $form->field($model, 'ativo') ?>

	<div class="form-group">
		<?= Html::submitButton('Cadastrar', ['class' => 'btn btn-primary']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

protected/modules/admin/views/produto/editar.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Produto - Editar';
?>


<div class="container">
	<div class="row">
		<h2 class="tituloGeral"><i class="fa fa-clone"></i> Produto - Editar</h2>
	</div>

	<?php
	$form = ActiveForm::begin(['id' => 'produto-form']); ?>
	
	<div class="col-md-6 sempadL">
		<?= $form->field($model, 'id_agenda')->dropDownList(yii\helpers\ArrayHelper::map($eventos, 'id', 'data', 'evento')) ?>
	</div>
	<div class="col-md-6 sempadR">
		<?= $form->field($model, 'nome') ?>
	</div>
	
	<?= $form->field($model, 'descricao')->textarea(['rows' =>5]) ?>

	<div class="col-md-3 sempadL">
		<?= $form->field($model, 'valor') ?>
	</div>
	<div class="col-md-3 sempadR">
		<?= $form->field($model, 'descontoFixo') ?>
	</div>
	<div class="col-md-3 sempadR">
		<?= $form->field($model, 'descontoPercentual') ?>
	</div>
	<div class="col-md-3 sempadR">
		<?= $form->field($model, 'ativo') ?>
	</div>

	<div class="form-group">
		<?= Html::submitButton('Salvar', ['class' => 'btn btn-primary']) ?>
	</div>

	<?php ActiveForm::end(); ?>
	
</div>

protected/modules/admin/views/produto/excluir.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Produto - Excluir';
?>
<h1><span style="font-weight:200;">Produto</span> - Excluir</h1>
<h2><?=$produto->nome?></h2>
<p>Tem certeza que quer excluir esse produto? Esta ação não pode ser revertida</p>
<?php
$form = ActiveForm::begin(['id' => 'produto-excluir']); ?>

<?= $form->field($produto, 'codigo')->hiddenInput()->label(false) ?>

<div class="form-group">
    <?= Html::submitButton('Sim, excluir', ['class' => 'btn btn-warning']) ?>
    <?= Html::button('Voltar', ['class' => 'btn btn-default', 'onclick'=>'javascript:history.back()']) ?>
</div>

<?php ActiveForm::end(); ?>	

protected/modules/admin/views/produto/index.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\Tags;

$this->title = 'ADM Easy for Pay' . (isset($matriz) && $matriz == true ? ' (matriz)' : ''); 
?>

<div class="container">
	<div class="row">
		<h2 class="tituloGeral"><i class="fa fa-clone"></i> Produtos - Consultar</h2>
	</div>
	
	<?php $form = ActiveForm::begin(['id' => 'produto-form']); ?>
	<?= $form->field($produto, 'matriz')->hiddenInput(['value' => $matriz])->label(false); ?>
	<?= $form->field($produto, 'id_agenda')->dropDownList(ArrayHelper::map($eventos, 'id', 'data', 'evento')) ?>
	<div class="form-group" style="text-align:center; margin-top:30px;">
		<?= Html::submitButton('Consultar', ['class' => 'btn btn-primary']) ?>
	</div>
	<?php ActiveForm::end(); ?>

	
	<div class="gridAgenda5Out">
		<div class="gridAgenda5 gridAgendaHead">
			<div>Nome</div>
			<div>Descrição</div>
			<div>Valor</div>
			<div>Desc.Fixo</div>
			<div>Desc.Perc.</div>
			<div>Status</div>
			<div>Tags</div>
		</div>
		<?php
		if (!$produto->hasErrors() && $produto->lista) {
			foreach ($produto->lista as $p) { 
		?>
			<div class="gridAgenda5">
				<div><h3><a href="<?=Url::to(['registro-produto','produto'=>$p->codigo])?>"><?=$p->nome?></a></h3></div>
				<div><p><?=$p->descricao?></p></div>
				<div><p>R$ <?=number_format($p->valor,2,'.',',')?></p></div>
				<div><p>Desconto fixo: <?=$p->descontoFixo?></p></div>
				<div><p>Desconto percentual: <?=$p->descontoPercentual?></p></div>
				<div><p>Status: <?=$p->ativo?></p></div>
				<div><p>Tags:<?= isset($p->tags) ? Tags::stringTags($p->tags) : 'nenhuma'; ?></p></div>
			</div>
			<?php
			}
		}
		?>
	</div>
</div>

protected/modules/admin/views/produto/modal-assentos.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\MaskedInput;
use yii\bootstrap\Modal;

Modal::begin([
    'header' => '<h4 align="center" id="title-assento">Assentos</h4>',
    'size'   => 'modal-md',
    'id'     => 'modal-assento',
    'options'=> [
        'class' => 'modal-center'
    ],
    'clientOptions' => [
        'keyboard' => false,
        'backdrop' => 'static',
    ]
]);

$tags->scenario = 'create';

$form = ActiveForm::begin([
    'id' => 'assento-form', 
    'action' => Url::to(['produto/novo-assento'])
]); ?>

<?php $model->ativo = '1'; ?>

<?= $form->field($model, 'id_agenda')->hiddenInput(['id' => 'id_agenda'])->label(false); ?>
<?= $form->field($model, 'nome')->hiddenInput()->label(false); ?>
<?= $form->field($model, 'valor')->hiddenInput(['value' => '0'])->label(false); ?>
<?= $form->field($model, 'descricao')->hiddenInput()->label(false); ?>
<?= $form->field($model, 'ativo')->radioList(['1' => 'Ativo', '0' => 'Inativo'])->label('Status'); ?>
<?= $form->field($tags, '[0]nome')->hiddenInput(['value' => 'matriz'])->label(false); ?>
<?= $form->field($tags, '[0]valor')->hiddenInput(['id' => 'tag-matriz'])->label(false); ?>
<?= $form->field($tags, '[1]nome')->hiddenInput(['value' => 'setor'])->label(false); ?>
<?= $form->field($tags, '[1]valor')->hiddenInput(['id' => 'tag-setor'])->label(false); ?>
<?= $form->field($tags, '[2]nome')->hiddenInput(['value' => 'fileira'])->label(false); ?>
<?= $form->field($tags, '[2]valor')->hiddenInput(['id' => 'tag-fileira'])->label(false); ?>
<?= $form->field($tags, '[3]nome')->hiddenInput(['value' => 'tipo'])->label(false); ?>
<?= $form->field($tags, '[3]valor')->hiddenInput(['value' => 'assento'])->label(false); ?>

<div class="row">
    <div class="col-xs-6">
        <?= $form->field($tags, '[4]nome')->hiddenInput(['value' => 'assento'])->label(false); ?>
        <?= $form->field($tags, '[4]valor')->textInput()->widget(MaskedInput::className(), [
            'mask' => '99',
            'options' => [
                'class' => 'form-control',
                'placeholder' => 'Número inicial do assento',
                'title' => 'Número inicial do assento',
                'id' => 'assento-ini'
            ],
            'clientOptions' => [
                'removeMaskOnSubmit' => true
            ]
        ])->label('do assento:');?>
    </div>
    <div class="col-xs-6">
        <?= $form->field($tags, '[5]nome')->hiddenInput(['value' => 'assento'])->label(false); ?>
        <?= $form->field($tags, '[5]valor')->textInput()->widget(MaskedInput::className(), [
            'mask' => '99',
            'options' => [
                'class' => 'form-control',
                'placeholder' => 'Número final do assento',
                'title' => 'Número final do assento',
                'id' => 'assento-fim'
            ],
            'clientOptions' => [
                'removeMaskOnSubmit' => true
            ]
        ])->label('até assento:');?>
    </div>
</div>

<?= Html::submitButton('Cadastrar', ['class' => 'btn btn-primary', 'id' => 'btn-novo-assento']); ?>

<?php ActiveForm::end(); ?>

<?php Modal::end(); ?>

protected/modules/admin/views/produto/modal-fileira.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\MaskedInput;
use yii\bootstrap\Modal;

Modal::begin([
    'header' => '<h4 align="center" id="title-fileira">Fileiras</h4>',
    'size'   => 'modal-md',
    'id'     => 'modal-fileira',
    'options'=> [
        'class' => 'modal-center'
    ],
    'clientOptions' => [
        'keyboard' => false,
        'backdrop' => 'static',
    ]
]);

$tags->scenario = 'create';

$form = ActiveForm::begin([
    'id' => 'fileira-form', 
    'action' => Url::to(['produto/nova-fileira'])
]); ?>

<?php $model->ativo = '1'; ?>

<?= $form->field($model, 'id_agenda')->hiddenInput(['id' => 'id_agenda'])->label(false); ?>
<?= $form->field($model, 'nome')->hiddenInput()->label(false); ?>
<?= $form->field($model, 'valor')->hiddenInput(['value' => '0'])->label(false); ?>
<?= $form->field($model, 'descricao')->hiddenInput()->label(false); ?>
<?= $form->field($model, 'ativo')->radioList(['1' => 'Ativo', '0' => 'Inativo'])->label('Status'); ?>
<?= $form->field($tags, '[0]nome')->hiddenInput(['value' => 'matriz'])->label(false); ?>
<?= $form->field($tags, '[0]valor')->hiddenInput(['id' => 'tag-matriz'])->label(false); ?>
<?= $form->field($tags, '[1]nome')->hiddenInput(['value' => 'setor'])->label(false); ?>
<?= $form->field($tags, '[1]valor')->hiddenInput(['id' => 'tag-setor'])->label(false); ?>
<?= $form->field($tags, '[2]nome')->hiddenInput(['value' => 'tipo'])->label(false); ?>
<?= $form->field($tags, '[2]valor')->hiddenInput(['value' => 'fileira'])->label(false); ?>

<div class="row">
    <div class="col-xs-6">
        <?= $form->field($tags, '[3]nome')->hiddenInput(['value' => 'fileira'])->label(false); ?>
        <?= $form->field($tags, '[3]valor')->textInput()->widget(MaskedInput::className(), [
            'mask' => '**',
            'options' => [
                'class' => 'form-control',
                'placeholder' => 'Letra inicial da fileira',
                'title' => 'Letra inicial da fileira',
                'id' => 'fileira-ini'
            ],
            'clientOptions' => [
                'removeMaskOnSubmit' => true
            ]
        ])->label('de fileira:');?>
    </div>
    <div class="col-xs-6">
        <?= $form->field($tags, '[4]nome')->hiddenInput(['value' => 'fileira'])->label(false); ?>
        <?= $form->field($tags, '[4]valor')->textInput()->widget(MaskedInput::className(), [
            'mask' => '**',
            'options' => [
                'class' => 'form-control',
                'placeholder' => 'Letra final da fileira',
                'title' => 'Letra final da fileira',
                'id' => 'fileira-fim'
            ],
            'clientOptions' => [
                'removeMaskOnSubmit' => true
            ]
        ])->label('até fileira:');?>
    </div>
</div>

<?= Html::submitButton('Cadastrar', ['class' => 'btn btn-primary', 'id' => 'btn-nova-fileira']); ?>

<?php ActiveForm::end(); ?>

<?php Modal::end(); ?>