protected/models/Agenda.php
<?php
namespace app\models;

use Yii;
use yii\base\Model;
use app\models\WsAgenda;
use app\models\Anexos;
use app\models\Cliente;
use yii\web\UploadedFile;
use app\models\Tags;

class Agenda extends Model {

    public $lista;
    public $codigo;
    public $nome;
    public $descricao;
    public $dataInicial;
    public $dataFinal;
    public $dataAtivar;
    public $dataDesativar;
    public $ativo;
    public $tags;
    public $anexos;
    public $destaques;
    public $produtos;
    public $data;
    public $datas;
    public $unidade;
    public $primeiroHorario;
    public $tipoEvento;

    //cadastro completo
    public $sinopse;
    public $direcao;
    public $atores;
    public $premios;
    public $duracao;
    public $classificacao;
    public $cupom;

    //anexos
    public $imgEvento;
    public $imgMosaico;
    public $imgDestaque;
    public $imgDestaqueApp;

    //tags
    public $destaque;

    //produtos
    public $preco;

    //empresa
    public $empresa;

    //espaços
    public $listaEspacos;
    public $espaco;

    // eventos em cartaz
    public $listaEmCartaz;
    
    /**
     * Método construtor sempre pede a unidade atual
    */
    public function __construct(Cliente $unidade){
        $this->unidade = $unidade;
    }

    /**
     * Regras de validação. Nome, data e ativo são obrigatórios (data é um array com dois ou três índices)
     */
    public function rules() {
        return [
            [['nome', 'dataInicial', 'dataFinal', 'ativo'], 'required'],
            [['descricao'], 'required', 'on'=>'novoEvento'],
            [['nome', 'dataInicial', 'dataFinal', 'ativo', 'imgEvento', 'duracao', 'preco', 'espaco'], 'required', 'on'=>'novoEventoCompleto'],
            [['nome', 'dataInicial', 'dataFinal', 'ativo', 'duracao'], 'required', 'on'=>'update'],
            [['data'], 'required', 'on'=>'novaData'],
            [['descricao', 'sinopse', 'data', 'datas', 'dataAtivar', 'dataDesativar', 'direcao', 'atores', 'premios', 'classificacao', 'destaque', 'imgMosaico', 'imgDestaque', 'imgDestaqueApp', 'cupom', 'tipoEvento'], 'safe'],
        ];
    }

    /**
     * definição dos labels de atributos
     */
    public function attributeLabels() {
        return[
            'lista' => 'Lista',
            'nome' => 'Nome',
            'descricao' => 'Descrição',
            'dataInicial' => 'Início do evento',
            'dataFinal' => 'Fim do evento',
            'dataAtivar' => 'Exibir no site em',
            'dataDesativar' => 'Remover exibição do site em',
            'data' => 'Data',
            'datas' => 'Datas',
            'ativo' => 'Ativo',
            'tags' => 'Tags',
            'anexos' => 'Anexos',
            'sinopse' => 'Ficha técnica - Sinopse',
            'direcao' => 'Ficha técnica - Direção',
            'atores' => 'Atores',
            'premios' => 'Prêmios',
            'duracao' => 'Duração',
            'classificacao' => 'Classificação etária',
            'destaque' => 'Evento em destaque',
            // 'destaque' => 'Evento em destaque (marque para habilitar o upload da imagem)',
            'preco' => 'Preço dos ingressos',
            'cupom' => 'Cupom',
            'espaco' => 'Espaço',
            'listaEspacos' => 'Espaço',
        ];
    }

    /**
     * Consulta eventos com a tag destaque=1 e com anexo imgDestaque
     */
    public function listaEventosDestaque($rede=0) {
        $wsAgenda=new WsAgenda($this->unidade->user_token);
        $filtro = ['ativo' => 1, 'tags'=>[['nome'=>'destaque','valor'=>'1']], 'rede'=>(int)$rede];
        $eventos = $wsAgenda->listarEventos($filtro);
        if (!$eventos->successo)
            return $this->addError('destaques', $eventos->erro->mensagem);

        foreach ($eventos->objeto as $evento) {
            if(!isset($evento->anexos)) continue;
            $evento->anexos=Anexos::objetoAnexos($evento->anexos);
            if (time() > strtotime(\DateTime::createFromFormat('d/m/Y H:i:s',$evento->data->final)->format('Y-m-d H:i:s')) || !isset($evento->anexos->imgDestaque))
                continue;

            $obj=new Agenda($this->unidade);
            $obj->loadFromApi($evento);
            $this->destaques[] = $obj;
        }
    }

    /**
     * Consulta eventos com ativo=1 desconsiderando os que tem data final no passado e o evento matriz da unidade
     * @param bool $rede se a pesquisa será feita em toda a rede ou apenas na unidade atual. O padrão é true
     * @todo dar a opção de desconsiderar os destaques que estiverem presentes em $this->destaques
     */
    public function listaEventosPublicosFuturo($rede=1) {
        $wsAgenda=new WsAgenda($this->unidade->user_token);
        $filtro = ['ativo' => 1, 'rede'=>(int)$rede];
        
        $eventos = $wsAgenda->listarEventos($filtro);
        if (!$eventos->successo)
            return $this->addError('lista', $eventos->erro->mensagem);

        foreach ($eventos->objeto as $evento) {
            $obj=new Agenda($this->unidade);
            $obj->loadFromApi($evento);
            // não mostrar eventos no passado
            if (time() > strtotime(\DateTime::createFromFormat('d/m/Y H:i:s',$obj->dataFinal)->format('Y-m-d H:i:s')))
                continue;
            // não mostrar eventos que tiverem definição de data ativar/desativar
            if($this->eventoNaoAtivo($obj, time()))
                continue;
            // separar eventos em cartaz em outra lista
            if($this->eventoEmCartaz($obj,time())){
                $this->listaEmCartaz[]=$obj;
                continue;
            }
            // ignorar eventos com nome MATRIZ (só usados internamente)
            if($obj->nome=='MATRIZ')
                continue;
            $this->lista[] = $obj;
        }
    }

    /**
     * Consulta todos os eventos. Espera-se que o user_token esteja na propriedade $unidade
     * @param string $ignore Informação que precisa ser ignorada
     */
    public function listaTodosEventos($ignore='') {
        $api = new WsAgenda($this->unidade->user_token);
        $eventos = $api->listarEventos();
        if (!$eventos->successo)
            return $this->addError('lista', $eventos->erro->mensagem);

        foreach ($eventos->objeto as $evento) {
            if ($ignore == '' || (!empty($ignore) && !stristr($evento->nome, $ignore))) {
                $obj = new Agenda($this->unidade);
                $obj->loadFromApi($evento);
                $this->lista[] = $obj;
            }
        }
    }

    /**
     * Consulta um evento pelo código
     */
    public function umEvento() {
        $api = new WsAgenda($this->unidade->user_token);
        // $evento = $api->buscarEventoRede($this->codigo,['rede'=>1]);
        $evento = $api->buscarEvento($this->codigo);
        if (!$evento->successo)
            return $this->addError('codigo', $evento->erro->mensagem);

        $this->loadFromApi($evento->objeto[0]);
        
        if($this->nome=='MATRIZ')
            return $this->addError('codigo', 'Evento não encontrado');
        
        $this->anexos=(new Anexos)->objetoAnexos($this->anexos,0);
        
    }

    public function selecionouOutraUnidade($unidade)
    {   
        $session = Yii::$app->session;
        $session->open();        
        $documento_unidade = $session->get('documento_unidade',false);
        if(!empty($documento_unidade) && $documento_unidade != $unidade ){
            $mensagem = "Você já iniciou uma compra com outra unidade. Finalize-a antes de comprar para outro evento";
            return (object) ['successo'=>'0', 'erro'=>['mensagem'=>$mensagem]];
        }
        return (object)['successo'=>'1'];
    }    

    /**
     * Organizar as datas de forma que os horários de um mesmo dia fiquem agrupados e não repita o mesmo dia com horários diferentes
     */
    public function separarHorariosDoMesmoDia(){
        $_dias=[];
        foreach ($this->datas as $data) {
            $_dias[$data->dia]['horarios'][]=['id'=>$data->id,'hora'=>$data->hora];
        }
        $this->primeiroHorario=$this->datas[0]->id;
        return $_dias;
    }

    /**
     * Cadastrar novo evento. Deve seguir as regras de validação (método rules)
     * @todo somente um usuário logado como operador 
     */
    public function criarEvento() {
        if ($this->validate()) {
            $api = new WsAgenda($this->unidade->user_token);
            $cadastro = $api->criarEvento([
                'nome' => $this->nome,
                'descricao' => $this->direcao,
                'data' => [
                    'inicial' => $this->dataInicial,
                    'final' => $this->dataFinal,
                    'ativar' => $this->dataAtivar,
                    'desativar' => $this->dataDesativar
                ],
                'ativo' => $this->ativo,
                'sinopse' => $this->sinopse,
                'direcao' => $this->direcao,
                'atores' => $this->atores,
                'premios' => $this->premios,
                'duracao' => $this->duracao,
                'classificacao' => $this->classificacao,
            ]);
            /*echo "<pre>";
            echo 'criarEvento <br />';
            print_r($cadastro);
            echo "</pre>";*/
            if (!$cadastro->successo){
                $this->addError('nome', $cadastro->erro->mensagem);
                return false;
            }
            $this->codigo=$cadastro->objeto->codigo;
            return true;
        }
    }

    /**
     * upload das imagens do evento
     * @param string $attr o atributo desse model o qual a imagem se refere
     * @param int $evento 
     */
    private function uploadImgEvento($attr,$post){
        $modelAnexos=new Anexos;
        $modelAnexos->scenario='create';
        $modelAnexos->load($post);
        $modelAnexos->imgBase64(UploadedFile::getInstance($modelAnexos, $attr));            
        if($modelAnexos->validate()){

protected/controllers/AgendaController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Response;
use app\controllers\ClienteController;
use app\models\Agenda;
use app\models\Cliente;
use app\models\Carrinho;
use app\models\Tags;
use app\models\Cupom;
use app\models\Produto;

class AgendaController extends ClienteController
{

    /**
     * Mostrar evento. Exibe apenas um se for passado o ID pelo parâmetro $evento, caso contrário retorna um erro
     * O método getMapa do objeto Mapa criado no render pede como parâmetros o primeiro horário registrado e a matriz (unidade)
     * @param integer $evento Id do evento
     * @return string
     */
    public function actionIndex($evento)
    {
        $session = Yii::$app->session;
        $session->open();
        $tokenEmSessao=$session->get('token_unidade',false);
        $objApiCliente = new Cliente;
        if($tokenEmSessao!==$objApiCliente->getTokenMatriz())
            $session->set('lista_unidades',null);
        $objApiCliente->buscarUnidadePor('user_token',$objApiCliente->getTokenMatriz());
        $session->set('token_unidade',$objApiCliente->user_token);
        $agenda = new Agenda($objApiCliente);
        $agenda->codigo = $evento;
        $agenda->umEvento();
        //$objApiCliente->buscarUnidadePor('documento',$agenda->empresa->documento);
        $tags = new Tags();
        $tagAgenda = $tags->arrayTags($agenda->tags);
        if ($agenda->hasErrors() || !$agenda->ativo) {
            return $this->render('/site/error',['name'=>'Evento não disponível', 'message'=>'Evento não disponível']);
        }

        $produtoApi=new Produto($objApiCliente);
        $produtoApi->buscarProdutosFiltro(['id_agenda'=>$agenda->datas[0]->id]);
        
        $carrinho = (new Carrinho($objApiCliente))->consultarCarrinho();
        $session->set('cobrar_taxa',false);
        
        if(isset($carrinho->objeto,$carrinho->objeto->produtos) && $produtoApi->lista[0]->codigo!=$carrinho->objeto->produtos[0]->codigo){
            return $this->render('compra-em-andamento', [
                'evento' => $agenda,
                'tags' => $tagAgenda,
            ]);
        }

        return $this->render('evento', [
            'outroEvento' => $agenda->selecionouOutraUnidade($agenda->empresa->documento),
            'evento' => $agenda,
            'horarios' => $agenda->separarHorariosDoMesmoDia(),
            'tags' => $tagAgenda,
            'tipoAssento' => $tagAgenda['assento'],
            'carrinho' => $carrinho,
            'produtos'=>$produtoApi->lista,
        ]);
    }

    /**
     * Mostrar evento especial para venda externa.
     * Semelhante ao actionIndex, porém este pede um código de um cupom privado que permite uma compra especial
     * @param integer $evento Id do evento
     * @param string $cupom o código do cupom
     */
    public function actionVendaExterna($evento,$cupom)
    {
        $session = Yii::$app->session;
        $session->open();
        $objApiCliente = new Cliente;
        $objApiCliente->buscarUnidadePor('user_token',$objApiCliente->getTokenMatriz());
        
        $agenda = new Agenda($objApiCliente);
        $agenda->codigo = $evento;
        $agenda->umEvento();
        $primeiroEvento=$agenda->separarHorariosDoMesmoDia();
        $objApiCliente->buscarUnidadePor('documento',$agenda->empresa->documento);
        $session->set('token_unidade',$objApiCliente->user_token);
        
        $tags = new Tags();
        $tagAgenda = $tags->objetoTags($agenda->tags);
        
        $objCupom=new Cupom($objApiCliente);
        $objCupom->buscarCupom(['id'=>$cupom]);
        $cupomOk=$agenda->checkCupom($objCupom,$evento,$primeiroEvento[key($primeiroEvento)]['horarios'][0]);
        
        if ($agenda->hasErrors()) {
            $msgErro='Evento não disponível';
            if(!$cupomOk)
                $msgErro=$agenda->getErrors('cupom')[0];
            return $this->render('/site/error',['name'=>'Evento não disponível', 'message'=>$msgErro]);
        }
        $session->set('cobrar_taxa',true);
        return $this->render('evento', [
            'outroEvento' => $agenda->selecionouOutraUnidade($agenda->empresa->documento),
            'evento' => $agenda,
            'horarios' => $primeiroEvento,
            'tags' => $tagAgenda,
            'tipoAssento' => $tagAgenda->assento,
            'carrinho' => (new Carrinho($objApiCliente))->consultarCarrinho()
        ]);
    }

    /**
     * Trazer a quantidade de produtos do evento atual (utilizado para produtos livres)
     * @param int $data código da data do evento sendo exibido
    */
    public function actionQtdeProdutos($data){
        $session = Yii::$app->session;
        $session->open();
        $token=$session->get('token_unidade',false);
        if (!Yii::$app->request->isAjax || !$token) return false;
        $objApiCliente = new Cliente;
        $objApiCliente->buscarUnidadePor('user_token',$token);
        
        if(Yii::$app->request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            $qtde=Carrinho::qtdeProdutosEvento((new Carrinho($objApiCliente))->consultarCarrinho(),$data);
            if($qtde>0)
                return ['successo'=>'1','objeto'=>['qtde'=>$qtde]];
            return ['successo'=>'0','erro'=>['mensagem'=>'Falha ao consultar a quantidade']];
        }
        
    }
}

protected/views/agenda/compra-em-andamento.php
<?php
use \app\assets\LightboxAsset;
use \app\assets\SlickAsset;
use \app\models\Agenda;
use app\models\Tags;
use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\CarrouselSimplesAsset; 
use app\components\TempoCarrinhoWidget;

CarrouselSimplesAsset::register($this);
LightboxAsset::register($this);
SlickAsset::register($this);

$session = Yii::$app->session;
$session->open(); 
?>
<div class="row">
    <div class="col-sm-12 semPad semMargin">
        <div class="alert alert-warning" style="font-size:16px; text-align:center;">
            Você já iniciou a compra de outro tipo de evento
        </div>
    </div>
    <p class="col-xs-6 text-right"><a class="btn btn-primary btn-lg" href="<?= Url::to(['/compra/concluir-compra-mineirao']) ?>">Concluir compra</a></p>
    <p class="col-xs-6 text-left"><a class="btn btn-primary btn-lg" href="<?= Url::to(['/compra/nova-compra']) ?>">Iniciar nova compra</a></p>
</div>

protected/views/agenda/selecaoProdutos.php
<?php
use yii\jui\Slider;
use yii\helpers\Url;
use \app\assets\MapaAsset;
use app\assets\EventoAsset;
use app\models\Tags;
use app\models\Mapa;

MapaAsset::register($this);
EventoAsset::register($this);
?>

<div class="deslizante" title="Zoom">
    <?= Slider::widget([
        'id' => 'zoomMapa',
        'clientOptions' => [
            'min' => 1,
            'max' => 200,
            'range' => 'min',
            'orientation' => 'vertical'
        ],
        'clientEvents' => [
            'create' => 'function() {
                zoomMapaReset();
                zoomMapaInit();
            }'
        ],
    ]);?>
</div>

<div class="col-md-9 semPad semMargin">
    <div class="blocoIngr1 mapa-selecao" id="holder-mapa" style="margin-top:0px;">
        <div class="div-loading">
            <div id="img-loading"></div>
        </div>
        <?= (new Mapa)->getMapa($evento->primeiroHorario); ?>
    </div>
    <div class="legendaMapa">
        <span id="circle1"></span> Livre
        <span id="circle2"></span> Reservado
        <span id="circle3"></span> Indisponível
        <span id="circle4"><p style="position:absolute; top:-3px; left:1px;">&#xf007;</p><p style="position:absolute; top:-3px; left:7px;">&#xf067;</p></span> Obeso
        <span id="circle5"><p style="position:absolute; top:-3px; left:3px;">&#xf193;</p></span> Cadeirante
        <span id="circle6"><p style="position:absolute; top:-3px; left:3px;">&#xf29d;</p></span> Mob.Reduzida		
    </div>
</div>

<div class="col-md-3 semPad semMargin">
    <input type="hidden" id="url-add-produto" value="<?= Url::to(['compra/adicionar-produto-carrinho']); ?>">
    <input type="hidden" id="url-del-produto" value="<?= Url::to(['compra/remover-produto-carrinho']); ?>">
    <input type="hidden" id="url-ocupantes" value="<?= Url::to(['compra/ingresso']); ?>">
    <input type="hidden" id="evento" value="<?= $_GET['evento']; ?>">
    <input type="hidden" id="data" value="<?= $evento->datas[0]->id; ?>">
    <span id="setaEsq"></span>
    <div class="blocoIngr2 font-assentos row" style="margin-top:0px;">
        <h2>Assentos selecionados</h2>
        <hr style="margin-top:10px; margin-bottom:10px; border-bottom: groove 2px #fff!important;">
        <div class="caixa-assentos barScroll">
            <form id="form-selecionados">
                <div id="assentos-selecionados" align="center">
                    <?php 
                    if (isset($carrinho->objeto->produtos) && !empty($carrinho->objeto->produtos)) {
                        $tags = new Tags();
                        foreach($carrinho->objeto->produtos as $index => $produto) {
                            if(!isset($produto->tags)) continue;
                            $tagsTmp = $tags->objetoTags($produto->tags);
                    ?>
                    <div id="div-<?= $produto->codigo; ?>" class="col-xs-3 selecionado idData-<?=$produto->agenda->id_data_agenda?>">
                        <div class="div-circle">
                            <?= $tagsTmp->fileira . '-' . $tagsTmp->assento; ?>
                        </div>
                    </div>
                    <?php
                        }
                    } 
                    ?>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="col-sm-6 totProd" id="total-itens-carrinho">
                <i class="material-icons text-left" title="Carrinho de compras" style="font-size:14px;">shopping_cart</i>
                <span class="itensNoCarrinho"></span> 
            </div> 
            <div class="col-sm-6">
                <input type="button" id="btn-assentos" class="btn btn-primary btn-assentos" value="Continuar" disabled>
            </div> 
		</div>
    </div>
</div>
<br clear="all">

protected/views/agenda/selecaoProdutosLivre.php
<?php
use yii\helpers\Url;
use \app\assets\MapaAsset;
use app\assets\EventoAsset;
use app\models\Mapa;

EventoAsset::register($this);
MapaAsset::register($this);
?>
<div class="col-md-9 semPad semMargin" id="boxdomapa">
    <!-- <p class="toolTipAl2">Mapa ilustrativo</p> -->
    <div class="blocoIngr1" id="holder-mapa">
        <div class="div-loading">
            <div id="img-loading"></div>
        </div>
        <div style="text-align:center;" class="infoMapa">
            <br>
            <p class="boxAsstL">Mapa <strong>ILUSTRATIVO</strong>. Os assentos são de livre escolha, compre ao lado.</p>
            <?= Mapa::getMapaLivre($tags->mapa); ?>
        </div>
    </div>
    <div class="legendaMapa">
    </div>
</div>

<div class="col-md-3 semPad semMargin">
    <input type="hidden" id="url-add-produto" value="<?= Url::to(['compra/adicionar-produto-carrinho']); ?>">
    <input type="hidden" id="url-del-produto" value="<?= Url::to(['compra/remover-produto-carrinho']); ?>">
    <input type="hidden" id="url-ocupantes" value="<?= Url::to(['compra/ingresso']); ?>">
    <input type="hidden" id="url-qtd-produto" value="<?= Url::to(['agenda/qtde-produtos']); ?>">
    <input type="hidden" id="evento" value="<?= $evento->codigo; ?>">
    <input type="hidden" id="data" value="<?=$evento->datas[0]->id?>">
    <span id="setaEsq"></span>
    <div class="blocoIngr2 font-assentos row">
        <h2>Ingressos</h2>
        <hr style="margin-top:10px; margin-bottom:10px; border-bottom: groove 2px #fff!important;">
        <div class="caixa-assentos barScroll semEscolhaAss"> 
            <div class="assQtd">
                <div><span style="font-family:'FontAwesome';">&#xf145;</span> Quantidade:</div><br>
                <input id="qtdeIngressos" type="number" min="1" max="20" value="1" style="text-align:center;">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 totProd" id="total-itens-carrinho">
                <i class="material-icons text-left" title="Carrinho de compras" style="font-size:14px;">shopping_cart</i>
                <span class="itensNoCarrinho"></span> 
            </div> 
            <div class="col-sm-6">
                <button id="btn-assentos" class="btn btn-primary btn-assentos" disabled>Continuar</button>
            </div> 
        </div>
    </div>
</div>
<br clear="all">

protected/views/agenda/selecaoProdutosMuseu.php
<?php
use yii\jui\Slider;
use yii\helpers\Url;
use \app\assets\MapaAsset;
use app\assets\EventoAsset;
use app\models\Tags;

MapaAsset::register($this);
EventoAsset::register($this);

?>
<div class="col-md-9 semPad semMargin" id="boxdomapa">
    <div class="blocoIngr1" id="holder-mapa">
        <div class="div-loading">
            <div id="img-loading"></div>
        </div>
        <?php if(isset($_GET['produtos']) && $_GET['produtos']=='dropdown')
            echo $this->render('/produtos/selecaoProdutosDropdown',['produtos'=>$evento->produtos]);
        ?>
		<div style="text-align:center;">
			<br>
			<p>Informe a quantidade desejada no box ao lado.</p>
            <img src="<?=Yii::getAlias("@web")?>/images/museu.jpg" style="width:70%;">
		</div>
    </div>
</div>

<div class="col-md-3 semPad semMargin">
    <input type="hidden" id="url-add-produto" value="<?= Url::to(['compra/adicionar-produto-carrinho']); ?>">
    <input type="hidden" id="url-del-produto" value="<?= Url::to(['compra/remover-produto-carrinho']); ?>">
    <input type="hidden" id="url-ocupantes" value="<?= Url::to(['compra/ingresso']); ?>">
    <input type="hidden" id="url-qtd-produto" value="<?= Url::to(['agenda/qtde-produtos']); ?>">
    <input type="hidden" id="evento" value="<?= $_GET['evento']; ?>">
    <input type="hidden" id="data" value="<?=$evento->datas[0]->id?>">
    <span id="setaEsq"></span>
    <div class="blocoIngr2 font-assentos row">
        <h2>Ingressos</h2>
        <hr style="margin-top:10px; margin-bottom:10px; border-bottom: groove 2px #fff!important;">
        <div class="caixa-assentos barScroll semEscolhaAss"> 
			<div class="assQtd">
                <div><span style="font-family:'FontAwesome';">&#xf145;</span> Quantidade:</div><br>
                <input id="qtdeIngressos" type="number" min="1" max="20" value="1" style="text-align:center;">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 totProd" id="total-itens-carrinho">
                <i class="material-icons text-left" title="Carrinho de compras" style="font-size:14px;">shopping_cart</i>
                <span class="itensNoCarrinho"></span> 
            </div> 
            <div class="col-sm-6">
                <button id="btn-assentos" class="btn btn-primary btn-assentos" disabled>Continuar</button>
            </div> 
		</div>
    </div>
</div>
<br clear="all">